<?php

require_once('../../../private/initialize.php');

//Checks to see if is a get request by checking ID, if not redirects to index
if(!isset($_GET['id'])) {
  redirect_to(url_for('/staff/workouts/index.php'));
}

// set ID Variable from get request
  #Set Workout ID variable from get request used in hidden field to redirect back to edit page
$id = $_GET['id'];
$workout_id = $_GET['workout_id'];
$mod = find_mod_by_id($id);

// handle post request generated by form in page
if(is_post_request()){
  $result = delete_mod($id);
  $workout_id = $_POST['workout_id'];
  echo $workout_id;
  redirect_to(url_for('/staff/workouts/edit.php?id=' . h(u($workout_id))));
}


$workout_title = 'Delete Mod';
include(SHARED_PATH . '/staff_header.php');

?>

<div id="content">
  <a class="back-link" href="<?php echo url_for('/staff/workouts/index.php'); ?>">&laquo; Back to List</a>
  <div class="delete mod">
    <h1>DELETE MOD</h1>
    <p><strong>Are you sure you want to delete this mod?<br />
      All exercises associated with this MOD will be deleted.  Press "Delete Mod" to continue</strong></p>
    <p>
      <?php
        $mod_type = find_mod_type_by_id($mod['mod_type_id']);
        $workout_name = find_workout_by_id($mod['workout_id']);
        echo h($mod_type['mod_type']) . " from " . h($workout_name['workout_name']);
      ?>
        </p>
    <form action="<?php echo url_for('staff/workouts/delete_mod.php?id=' . h(u($id)));?>" method="post">
      <div id="operations">
        <!-- Hidden field contains workout_id stored from get request to redirect using POST to edit page -->
        <input type="hidden" name="workout_id" value="<?= $workout_id ?>">
        <input type="submit" name="commit" value="Delete Mod" />
      </div>

  </div>

</div>
