<?php

require_once('../../../private/initialize.php');

//Checks to see if is a get request by checking ID, if not redirects to index
if(!isset($_GET['id'])) {
  redirect_to(url_for('/staff/workouts/index.php'));
}

// set ID Variable from get request
  #Set Workout ID variable from get request used in hidden field to redirect back to edit page
$id = $_GET['id'];
$workout_id = $_GET['workout_id'];

// handle post request generated by form in page
if(is_post_request()){
  $result = delete_workout_step($id);
  $workout_id = $_POST['workout_id'];
  redirect_to(url_for('/staff/workouts/edit.php?id=' . h(u($workout_id))));

// handle get request, search for current mod using id variable set at beginning of script
} else {
  $workout_step = find_workout_step_by_id($id);
}


$workout_title = 'Delete Workouts Step';
include(SHARED_PATH . '/staff_header.php');

?>

<div id="content">
  <a class="back-link" href="<?php echo url_for('/staff/workouts/index.php'); ?>">&laquo; Back to List</a>
  <div class="delete workout step">
    <h1>DELETE WORKOUT STEP: <?php
      $exercise_name = find_exercise_by_id($workout_step['exercise_id']);
      echo h($exercise_name['exercise_name']);
    ?></h1>
    <p><strong>Are you sure you want to delete this workout step?</strong></p>
    <form action="<?php echo url_for('staff/workouts/delete_workout_step.php?id=' . h(u($id)));?>" method="post">
      <div id="operations">
        <!-- Hidden field contains workout_id stored from get request to redirect using POST to edit page -->
        <input type="hidden" name="workout_id" value="<?= $workout_id ?>">
        <input type="submit" name="commit" value="Delete Workout Type" />
      </div>

  </div>

</div>
